### ISSUE TITLE
The non-abstract class '_TestFairyClientHttpRequest' is missing implementations

### ISSUE THREAD

**Issue by rubenvde** [testfairy/testfairy-flutter#17]
Hi,
I'm trying to compile my flutter project including this sdk of TestFairy but after the Xcode build is done I get this message:

```
    ** BUILD FAILED **


Xcode's output:
↳
    /usr/local/Caskroom/flutter/latest/flutter/.pub-cache/hosted/pub.dartlang.org/testfairy-1.0.20/lib/src/network_logging.dart:253:7: Error: The non-abstract class '_TestFairyClientHttpRequest' is missing implementations for these members:
     - HttpClientRequest.abort
    Try to either
     - provide an implementation,
     - inherit an implementation from a superclass or mixin,
     - mark the class as abstract, or
     - provide a 'noSuchMethod' implementation.

    class _TestFairyClientHttpRequest implements HttpClientRequest {
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    org-dartlang-sdk:///third_party/dart/sdk/lib/_http/http.dart:2045:8: Context: 'HttpClientRequest.abort' is defined here.
      void abort([Object? exception, StackTrace? stackTrace]);
           ^^^^^

    Command PhaseScriptExecution failed with a nonzero exit code
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description

```

I have to say that I'm running early software: mac OS Big Sur beta 6 and Flutters master channel but I can't get rid of this error. I'm trying to run version 1.0.20 of the flutter TestFairy library. Hopefully someone can help me out.

**Comment by diegoperini** [comment]
Ho @rubenvde ,

We are aware of this potential issue. On the master branch, Flutter breaks backward compatibility by adopting new Dart syntax and adding a method to one of the classes we depend on. In order not to break people's code in the stable channel, we are holding our release. We will be ready in a timely manner once these changes are promoted to stable.

As a temporary workaround, I would suggest cloning this repo and using it as an offline dependency temporarily. That way, it becomes really easy to add the missing `abort()` method to `_TestFairyClientHttpRequest` yourself.

I'm keeping this issue open until the fix is published. If you subscribe to it, you will be notified once the update is ready.

Thanks for the notice.

**Comment by diegoperini** [comment]
Hi @rubenvde ,

We have a new update for the plugin which makes this migration process a little easier. You may want to check out [this guide](https://github.com/testfairy/testfairy-flutter#how-to-compile-with-latest-unreleased-flutter) to follow the steps. We also have a [blog post](https://testfairy.com/blog/developing-with-flutter-master-channel/) which explains the issue in depth. I'm closing this now until Flutter makes these changes official.

Thanks for hacking with TestFairy.
