### ISSUE TITLE
Error: The non-abstract class '_TestFairyClientHttpRequest' is missing implementations for these members:

### ISSUE THREAD

**Issue by neiljaywarner** [testfairy/testfairy-flutter#25]
```
.pub-cache/hosted/pub.dartlang.org/testfairy-1.0.8/lib/src/network_logging.dart:224:7: Error: The non-abstract class '_TestFairyClientHttpRequest' is missing implementations for these members:
 - HttpClientRequest.abort
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class _TestFairyClientHttpRequest implements HttpClientRequest {
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
org-dartlang-sdk:///third_party/dart/sdk/lib/_http/http.dart:2053:8: Context: 'HttpClientRequest.abort' is defined here.
  void abort([Object? exception, StackTrace? stackTrace]);
       ^^^^^
```
---
```
flutter doctor below
[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.15.5 19F101, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
[!] Android Studio (version 4.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] IntelliJ IDEA Community Edition (version 2020.2.3)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
 
[✓] Connected device (1 available)            

! Doctor found issues in 2 categories.
```

**Comment by neiljaywarner** [comment]
what's weird to me is that it worked a few months ago with the same configuration afaik.

**Comment by neiljaywarner** [comment]
I tried all 1.x versions in between and same error... i will try some different versions of http. here are my dependencies.
`
environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: 0.12.0+4

  testfairy: 1.0.25

  cloud_firestore: 0.13.4+2

  firebase_remote_config: 0.3.0+3

  flutter_email_sender: 2.2.2

  #firebase_auth: ^0.15.5+3

  login: 1.1.2




  

  
  # intl is for DateFormat etc (for datetimeformat, for the hh:mm a in time picker
  intl: ^0.16.1
  datetime_picker_formfield: ^1.0.0`

**Comment by neiljaywarner** [comment]
i tried all the versions of testfairy forward, all the versions of http forward and even an old version of `http` dependency - `http: 0.12.0` - the oldest that didn't give some other kind of error.

**Comment by diegoperini** [comment]
Hi @neiljaywarner 

Thank you for using this plugin. Allow me to explain the issue here.

Starting from Dart SDK 2.0.0, Flutter is transitioning towards Dart 2, which is backward incompatible with Dart 1 due to changes in the type system.

To be able to use TestFairy Flutter Plugin 2.+, you must have the environment specified below and upgrade your project code base to Dart 2 using [this guide](https://dart.dev/dart-2). 

```
environment:
  sdk: ">=2.10.0 <3.0.0"
  flutter: ">=1.22.0 <2.0.0"
```

Make sure your project root has an *analysis_options.yaml* that looks similar to [this](https://github.com/testfairy/testfairy-flutter/blob/master/analysis_options.yaml). The important part is the enabled experiment in the top declaration.

You also have to enable the same experiment in your run and test commands:

```
flutter run --enable-experiment=non-nullable --no-sound-null-safety

flutter drive --enable-experiment=non-nullable --no-sound-null-safety -v --target=test_driver/app.dart
```

If this transition is not suitable for your project, you can stay in TestFairy plugin 1.0.25 but that requires an upper limit on your Dart and Flutter version specified like this:

```
environment:
  sdk: ">=2.0.0 <2.1.0"
  flutter: ">=1.0.0 <1.12.0"
```

I hope this get rids of the error message you are seeing.

Let me know if the issue still persist after you make the changes above.

Thanks.

**Comment by neiljaywarner** [comment]
Hm.  You give two techniques, one of which for flutter <1.12 and one of which for flutter > 1.22
unfortunately I'm on flutter 1.17...

I guess I'll attempt to update and see how it goes...

**Comment by neiljaywarner** [comment]
Tried utilizing the analysis options file as mentioned, it still didn't work. I am pretty sure the analysis options file is in use (eg no typo) bc i had to sort out some changes in the file, restart the server, etc.

**Comment by diegoperini** [comment]
We know have `1.X.Y` releases for Dart 1 and `2.X.Y` releases for Dart 1, which should resolve this problem when chosen accordingly. I'm closing this issue for now. Please let us know if the issue persists. Thanks.
